### ISSUE TITLE
Use FastAPIWrapper for the API

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#12]
Having Swagger documentation for the API would be useful during development, and potentially for some end users.

``FastAPIWrapper`` is built on top of ``PiccoloCRUD``, so the API should be the same, but this needs to be verified.

**Comment by sinisaos** [comment]
Hi Daniel
I've been playing with this for a couple of days and I've managed to integrate FastAPIWrapper with small code changes (I don't know if they're the best but they work). 
1. FastAPIWrapper inherits from Starlette Router to be callable. Changes in piccolo_api fastapi `endpoints.py`
```
# new import
from starlette.routing import Router

class FastAPIWrapper(Router):
      # rest of unchanged code

      # at the end of FastAPIWrapper __init__ 
      super().__init__(routes=piccolo_crud.routes + fastapi_app.routes)

      # rest of unchanged code
```
2. In piccolo_admin `endpoints.py` I replaced table_routes with this
```
# new imports
from fastapi import FastAPI
from piccolo_api.fastapi.endpoints import FastAPIWrapper, FastAPIKwargs

# rest of unchanged code

table_routes: t.List[BaseRoute] = [
    Mount(
        path=f"/{table._meta.tablename}",
        app=FastAPIWrapper(
            root_url=f"/{table._meta.tablename}s",
            fastapi_app=FastAPI(),
            piccolo_crud=PiccoloCRUD(
                table=table,
                read_only=False,
            ),
            fastapi_kwargs=FastAPIKwargs(
                all_routes={
                    "tags": [f"{table._meta.tablename.capitalize()}"]
                },
            ),
        ),
    )
    for table in tables
]

# rest of unchanged code
```
Result is this

![docs](https://user-images.githubusercontent.com/30960668/105951275-0fa4e300-6070-11eb-8306-9fe909377f78.png)

With this we have all admin functions and Swagger docs per table. But there is one problem. In admin UI everything works great but in Swagger UI only GET method works and we can't use Piccolo `session auth` because [Cookie authentication currently does not work in Swagger UI](https://github.com/tiangolo/fastapi/issues/1900). Even curl doesn't work because I can't pass id and csrftoken cookies in api call (due the CSRFMiddleware). Even if I made separate OAuth or Apikey auth in FastAPI I can't use it because I don't know how to include csrftoken to Swagger UI form (like you do for admin Vue frontend app in `main.ts`) and CSRFMiddleware block call. I'm not an expert but I don't see point of using all of this if can't interact with all HTTP methods. Sorry for this long comment but I want to hear your opinion before any PR. Cheers.

**Comment by dantownsend** [comment]
@sinisaos It is very tricky - I'm impressed with how far you've gotten with it.

It's challenging because the API is built up dynamically.

I'm not sure what to do about cookie authentication not working. I guess the only authentication that is supported is OAuth. I know you implemented it in your example FastAPI app. Maybe that's an option.

I'll have a proper look this evening. Feel free to make a PR with what you have.

We might decide it just isn't viable. Having the API docs would definitely be nice, but it's a trade-off if we have to add a lot of complexity.

Thanks for looking into it.

**Comment by sinisaos** [comment]
@dantownsend Thanks. I think that with cookie authentication we can't do nothing because Swagger UI currently not support it for `"Try it out"` requests due to browser security restrictions. 
I already try OAuth and that's also dosen't work behind admin, because admin use session auth with CSRFMiddleware and you must provide csrftoken in Swagger UI forms to be able forms to work because otherwise you get `403 Forbidden`.
We need something like you do for admin Vue frontend app in `main.ts`


```
// Add the CSRF token
axios.interceptors.request.use(function (config) {
    if (
        ['POST', 'PUT', 'DELETE', 'PATCH'].indexOf(
            config.method.toUpperCase()
        ) != -1
    ) {
        const csrfToken = Cookies.get('csrftoken')
        config.headers['X-CSRFToken'] = csrfToken
    }
    return config
})

```

But I don't know how to implement this in Swagger UI. 

Later tonight or tomorrow I do PR in `piccolo_api` and `piccolo_admin`. Maybe you have some ideas about it.

**Comment by dantownsend** [comment]
Will mark this as done for now.
