### ISSUE TITLE
Feature Request: Make custom form message timeout configurable

### ISSUE THREAD

**Issue by ethagnawl** [piccolo-orm/piccolo_admin#169]
I'm using a custom form to allow admins to run a reporting routine and the output _can_ be pretty lengthy. It looks like the [current timeout](https://github.com/piccolo-orm/piccolo_admin/blob/569245afb0c2b6f0ae9bdc54df3f2f6032f7df0a/admin_ui/src/components/MessagePopup.vue#L51-L61) is 3 seconds and that's not enough time for the user to comprehensively review the output.

Would you be open to adding an optional property to the CustomForm class that would allow users to configure this -- and potentially other -- UI options?

**Comment by dantownsend** [comment]
I'm not against adding new config options to `FormConfig`.

I gave it a try with a really slow form endpoint to see what happens. The form gets processed OK. It would probably be better if it said 'saving' or something, and disabled the submit button so you can't accidentally submit the form multiple times.

https://user-images.githubusercontent.com/350976/175757226-28218f6b-4eb5-4648-967e-1a1749153c73.mov

I think I understand your issue though - if the endpoint returns a lengthy message that the user needs to read, they might not be able to read if because the message only shows for 3 seconds.

Maybe we could change the design, so rather than just showing the message in a popup, we redirect them to a success page with the message on, which has no timeout.

<img width="382" alt="Screenshot 2022-06-25 at 05 09 48" src="https://user-images.githubusercontent.com/350976/175757673-865991e8-f58e-4ad6-8ef6-fc9b13589aa7.png">

That way the form could even return a bunch of JSON or something that the user could copy.

**Comment by ethagnawl** [comment]
Thanks, yet again, for the prompt response, @dantownsend! 

> if the endpoint returns a lengthy message that the user needs to read, they might not be able to read if because the message only shows for 3 seconds.

That's exactly it. I also think your solve is an even better one that what I'd outlined. Though, I could still make the case for making the CustomForm UI more configurable (the timeout mentioned above, styles, input validation, etc.).

Let me know if you want help with a PR for the "success" page approach. (How would you envision errors being treated? as they currently are or as a message on this new page?)

**Comment by dantownsend** [comment]
@ethagnawl  If you want to give it a go that would be great. I'm happy to help, or finish if off if you hit any problems.

I think for errors, it's probably OK as it is for now.

**Comment by dantownsend** [comment]
@ethagnawl It looks good.

I was just thinking about the various ways of doing it. One really simple approach (which for some reason didn't occur to me until now) is to do something like this in `FormAdd.vue`:

```vue
<template>
    <div>
        <template v-if="formConfig">
            <h1>{{ formConfig.name }}</h1>

            <p v-if="formConfig.description">{{ formConfig.description }}</p>
        </template>

        <div v-show="successMessage">
            <p>{{ successMessage }}</p>
            <ul>
                <li>
                    <a href="#" @click.prevent="resetForm">Use again</a>
                </li>
                <li>
                    <router-link to="/">Back to home page</router-link>
                </li>
            </ul>
        </div>

        <div v-show="!successMessage">
            <pre>{{ errors }}</pre>

            <form
                v-if="schema"
                v-on:submit.prevent="submitForm($event)"
                ref="form"
            >
                <NewForm :schema="schema" />
                <button>Submit</button>
            </form>
        </div>
    </div>
</template>

<script lang="ts">
import axios from "axios"
import Vue from "vue"
import NewForm from "./NewForm.vue"
import { APIResponseMessage, FormConfig } from "../interfaces"

const BASE_URL = process.env.VUE_APP_BASE_URI

export default Vue.extend({
    props: {
        formSlug: String,
        schema: Object
    },
    components: {
        NewForm
    },
    data() {
        return {
            errors: "",
            formConfig: undefined as FormConfig,
            successMessage: null
        }
    },
    watch: {
        async formSlug() {
            await this.fetchFormConfig()
        }
    },
    methods: {
        resetForm() {
            this.$refs.form.reset()
            this.successMessage = null
        },
        async fetchFormConfig() {
            const response = await this.$store.dispatch(
                "fetchFormConfig",
                this.formSlug
            )
            this.formConfig = response.data
        },
        async submitForm(event: any) {
            const form = new FormData(event.target)

            const json = {}
            for (const i of form.entries()) {
                const key = i[0].split(" ").join("_")
                let value: any = i[1]

                if (value == "null") {
                    value = null
                } else if (this.schema.properties[key].type == "array") {
                    value = JSON.parse(value)
                }
                json[key] = value
            }

            try {
                var response = await axios.post(
                    `${BASE_URL}forms/${this.formSlug}/`,
                    json
                )
            } catch (error) {
                const data = error.response.data
                var message: APIResponseMessage = {
                    contents: "The form has errors.",
                    type: "error"
                }
                this.$store.commit("updateApiResponseMessage", message)

                if (typeof data != "string") {
                    this.errors = JSON.stringify(data, null, 2)
                } else {
                    this.errors = data
                }
                return
            }

            this.successMessage =
                response.data.message || "Successfully submitted form"
        }
    },
    async mounted() {
        await this.fetchFormConfig()
    }
})
</script>

<style scoped lang="less">
h1 {
    text-transform: capitalize;
}
</style>

```

So rather than having a separate component, it's all handled inside that single component.

**Comment by ethagnawl** [comment]
That _is_ simpler and would still be a nice improvement. I'm all for it.

**Comment by ethagnawl** [comment]
Thanks, @dantownsend! :pray:
