### ISSUE TITLE
WYSIWYG for admin

### ISSUE THREAD

**Issue by tigerline86** [piccolo-orm/piccolo_admin#172]
Hello!
Could you tell me please, how i make override rich_text_columns
I want to use TinyMCE editor for Text columns!

**Comment by sinisaos** [comment]
@tigerline86 In Piccolo Admin, we use the [vue2-editor](https://www.npmjs.com/package/vue2-editor) that uses Quill under the hood (among the most popular WYSIWYG editors for Vue). You can't override the vue2-editor, but you can integrate TinyMCE yourself (or another editor because the content is saved [here](https://github.com/piccolo-orm/piccolo_admin/blob/2fbdec3a63c919bc4c140b75ec5469b4921e78d0/admin_ui/src/components/InputField.vue#L65-L70) regardless of the WYSIWYG editor). Here is the changes you need to make in `InputField.vue`. 
```Vue
<template>
     ... // unchanged code
    <div v-else-if="format == 'text-area' && isFilter == false">
      <textarea
          v-if="
              !schema.rich_text_columns.includes(
                  getFieldName(title).toLowerCase()
              )
          "
          autocomplete="off"
          ref="textarea"
          v-bind:name="getFieldName(title)"
          v-bind:placeholder="placeholder"
          v-bind:style="{ height: textareaHeight }"
          v-model="localValue"
          v-on:input="setTextareaHeight"
      />
    
      <editor
          v-else
          v-model="localValue"
          api-key="no-api-key"
          :init="{
              height: 500,
              menubar: false,
              plugins: [
                  'advlist autolink lists link image charmap print preview anchor',
                  'searchreplace visualblocks code fullscreen',
                  'insertdatetime media table paste code help wordcount'
              ],
              toolbar:
                  'undo redo | formatselect | bold italic backcolor | \
                  alignleft aligncenter alignright alignjustify | \
                  bullist numlist outdent indent | removeformat | help'
          }"
      />
    
      <textarea
          id="editor"
          v-model.lazy="localValue"
          v-bind:name="getFieldName(title)"
      ></textarea>
    </div>

    ... // unchanged code

</template>

<script lang="ts">
import Vue, { PropType } from "vue"

import flatPickr from "vue-flatpickr-component"

import ArrayWidget from "./ArrayWidget.vue"
import ChoiceSelect from "./ChoiceSelect.vue"
import DurationWidget from "./DurationWidget.vue"
import OperatorField from "./OperatorField.vue"
import { Choices } from "../interfaces"
import Editor from "@tinymce/tinymce-vue"

export default Vue.extend({
    props: {
        title: {
            type: String,
            default: ""
        },
        type: {
            type: String,
            default: "string"
        },
        value: {
            type: undefined,
            default: undefined
        },
        // Fields can share the same type, but have different formats. For
        // example, 'text-area', when type is 'string'.
        format: String,
        isFilter: {
            type: Boolean,
            default: true
        },
        isNullable: {
            type: Boolean,
            default: false
        },
        choices: {
            type: Object as PropType<Choices>,
            default: null
        }
    },
    components: {
        flatPickr,
        ArrayWidget,
        ChoiceSelect,
        DurationWidget,
        OperatorField,
        editor: Editor
    },
    ... // unchanged code

</script>
```
Here is result:

![TinyMCE](https://user-images.githubusercontent.com/30960668/177045996-80845bec-4c50-4a66-9aa3-9312f8df45aa.png)

Hope this helps.

**Comment by dantownsend** [comment]
Yeah, it's hard for us to support multiple rich text editors, because the front end of Piccolo Admin is a Vue JS application, and each rich text editor we include increases the JavaScript bundle size quite dramatically.

We went for Quill, as it was quite easy to integrate, and looks decent.

The suggestion by @sinisaos works, but would mean forking the codebase. There's no easy way to configure a different editor.

If there's a particular feature you need, maybe we can configure Quill so it provides it.

**Comment by tigerline86** [comment]
thank you for answers!

highlighted in green in the screenshot
![Screenshot from 2022-07-04 15-16-36](https://user-images.githubusercontent.com/26675095/177153795-f1029f0f-40be-459a-b789-0a92cd13da4e.png)

and i use direct html editing

currently i need to change html in the database, i think this is a bad appoach

**Comment by sinisaos** [comment]
@dantownsend We are limited here. I can only configure Quill to this.

https://user-images.githubusercontent.com/30960668/177699589-021ba46f-56cd-42e2-802a-08dd1e9a81af.mp4

Based on an online search, the default Quill configuration doesn't work properly in Vue or React and I don't know why). If you are happy with this, I can make these changes.

**Comment by dantownsend** [comment]
@sinisaos Interesting.

Maybe we should just drop the font-family - not sure how useful this actually is (unless you're writing a code snippet and want a mono font). What do you think?

Similarly with the font size - not sure how useful that is.

I think the heading option is useful though, does that wrap the output in h1 / h2 / h3 tags etc?

I think we can assume that people using the rich text editor are doing it for a blog, and most of the styling can be done using CSS.

**Comment by dantownsend** [comment]
@sinisaos Yeah, let's add the headings option. I think it makes the rich text editor more useful for writing blog articles etc.

**Comment by sinisaos** [comment]
@dantownsend Ok. I will change that.

**Comment by tigerline86** [comment]
I think that such code editors are just used by people who are not familiar with programming. And it's convenient for them to just press a button and get the result.

Do you think it can give you the opportunity to choose a code editor when creating a project through the CLI? Is it difficult to implement?

**Comment by sinisaos** [comment]
@tigerline86 This is hard to do because Piccolo Admin is a Vue JS application (different from e.g. Django), and as @dantownsend  says, every rich text editor we include increases the size of the JavaScript bundle dramatically ([TinyMCE](https://bundlephobia.com/package/tinymce@6.1.0), [CKEditor](https://bundlephobia.com/package/ckeditor4@4.19.0)). Piccolo Admin is more like a React Admin that only supports [TipTap](https://marmelab.com/react-admin/doc/4.0/RichTextInput.html). Piccolo Admin creates the form fields from the Pydantic schema and in theory we could write a separate input field for each WYSIWYG editor as I gave the example in my first comment (the content is saved from [here](https://github.com/piccolo-orm/piccolo_admin/blob/master/admin_ui/src/components/InputField.vue#L65-L69) whatever WYSIWYG editor we use), but we come back to the bundle size which would be too big. Simplest would be to fork the codebase and do it yourself like the example I gave. That way you can use the WYSIWYG editor you want.

**Comment by dantownsend** [comment]
Yeah, I think it's unlikely we'll have multiple different WYSIWYG editors. But we can make sure the one we do have is really good. Quill seems pretty good - just need to make sure we configure it properly. Maybe we'll swap it out at some point if we find something better.

**Comment by sinisaos** [comment]
@dantownsend You can close this as it is done.
