### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by tigerline86** [piccolo-orm/piccolo_admin#181]
Hello!
Please tell me if there are any built-in mechanisms for uploading images in the admin panel?

**Comment by sinisaos** [comment]
@tigerline86 For now, there is no such possibility. There is already a issue #109 about that. I was able to upload images from the frontend using the Cloudinary widget (there is video about that), but we think that upload from the backend would be a better option because that way the user can write their own adapter to work with any storage provider they want (including  local storage).

**Comment by dantownsend** [comment]
Yeah, as @sinisaos says, we're working on it at the moment.

One hack is to use a rich text field, and add images there.

**Comment by sinisaos** [comment]
@dantownsend That's right. Quill is very good for this because you don't have to do any extra configuration to upload images. Everything simply works out of the box.

**Comment by dantownsend** [comment]
This has been implemented now:

https://piccolo-admin.readthedocs.io/en/latest/media_storage/index.html
