### ISSUE TITLE
Bug with nullable boolean columns in filters

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#279]
If you have a nullable boolean column, in the filter sidebar it defaults to `null` instead of `all`, and you get a Pydantic error when trying to submit the form with a value of `null`.

**Comment by sinisaos** [comment]
@dantownsend Sorry if I am wrong but we should remove `null` option for `boolean` select dropdown
https://github.com/piccolo-orm/piccolo_admin/blob/0dbb344ab4ead971a5ab9effc1de5b023a1f1a89/admin_ui/src/components/InputField.vue#L124-L130

because [only this values](https://docs.pydantic.dev/usage/types/#booleans) is allowed for `boolean` value in Pydantic.
