### ISSUE TITLE
Implement proxying in Vue CLI

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#86]
In the current contributing docs, it mentions having to setup a proxy server such as Nginx, so the front end and backend can be consumed from the same domain.

There is a feature built into Vue CLI, which will automatically proxy certain paths.

https://cli.vuejs.org/config/#devserver-proxy

This is easier than having to setup a separate proxy server.

If we implement this change, it might make it easier for people to get the Piccolo admin running locally.

**Comment by sinisaos** [comment]
@dantownsend Although this is a tempting idea it may not be the best solution because if we set up `devServer.proxy` we lose the benefits of FastAPI (`/api/docs/`, `/api/tables/` etc. don't work like warning in Vue docs says). `http-proxy-middleware` is compatible only with this [servers](https://github.com/chimurai/http-proxy-middleware#compatible-servers). I think we should stay on Nginx proxy server because setup is not that hard.

**Comment by dantownsend** [comment]
@sinisaos Ah interesting, I didn't realise there were those complications.

If you think the Nginx approach is OK, let's keep that for now then.
